Add tags, integrations and their related search options
fifty-six/Scarab pull request #107
Opened 2022-08-30 02:55 UTC by TheMulhima

image of what new UI looks like:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/81007262/187338302-237d71a0-685c-4130-aa40-60ea53b720a8.png">

2022-08-30 09:30 UTC, fifty-six requested changes

2022-08-30 09:30 UTC, fifty-six commented on Scarab/Models/ModItem.cs
> +        public string[]   Integrations { get; }
These should be marked as nullable, i.e. `string[]?`. You don't want to force comparisons with `null!`.

2022-08-30 09:30 UTC, fifty-six commented on Scarab/Services/ModDatabase.cs
> +                    integrations:mod.Integrations,
missing a space

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +            List<ModItem> AllDependents = new();
this should not be pascal case

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +            var searchedMod = GetMod(Search!);
`Search!` shouldn't be a thing, Search should be marked as nullable if it can be null and the `!` used here has no corresponding check.

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +        private bool RecursiveCheckDependency(ModItem Mod, ModItem ToSearchDependencyMod)
These shouldn't be PascalCase'd.

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +        private bool _normalSearch = true;
Should be using [Notify(...)] instead of writing properties by hand

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +            TagList = new ObservableCollection<string>()
These should not be magic strings

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +        private bool RecursiveCheckDependency(ModItem Mod, ModItem ToSearchDependencyMod)
This should also probably not be in this class, ideally only view logic should be here.

2022-08-30 09:30 UTC, fifty-six commented on Scarab/Models/ModLinks.cs
> +        public string[] Tags { get; set; }
Should be a nullable type.

2022-08-30 09:30 UTC, fifty-six commented on Scarab/Models/ModLinks.cs
> +        public string[] Integrations { get; set; }
Should also be a nullable type

2022-08-30 09:30 UTC, fifty-six commented on Scarab/Models/ModItem.cs
> +        public string   Name             { get; set; }
?

2022-08-30 09:30 UTC, fifty-six commented on Scarab/Models/ModLinks.cs
> +using System.Runtime.InteropServices;
why

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +        enum ModViewState
Explicit visibility modifier and several lines for enums please

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +                    if (mod.HasIntegrations)
This should just be pattern matching, the properties of `HasX` are only there for UI binding purposes

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +            if (searchedMod != null)
Should invert this if

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +        private bool RecursiveCheckDependency(ModItem Mod, ModItem ToSearchDependencyMod)
Should probably be called something like HasDependent or IsDependentOn or something idk, this name isn't descriptive.

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +        private void DisplayModsCorrectly()
This is terrible naming

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +                ModViewState.Enabled => newList.Where(x=> x.State is InstalledState { Enabled: true }),
space before the `=>`

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +        private ModItem? GetMod(string name)
Should probably have a dictionary or something initialized earlier because this is gonna take your DFS `n^2` time and is just generally kinda bad

2022-08-30 09:30 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +        public void SelectAll()
I'd prefer something like a `MVState` property where  you actually update the mods within  the setter so these aren't all the same thing with a call at the end

2022-08-30 09:30 UTC, fifty-six commented on Scarab/Views/ModListView.xaml
> +                    <ComboBox Items="{Binding TagList}" SelectedIndex="0" SelectedItem="{Binding SelectedTag}"></ComboBox>
`/>` instead of an extra closing tag

2022-08-30 09:30 UTC, fifty-six commented on Scarab/Views/ModListView.xaml
> +                <ComboBox
The stuff in this is not indented correctly

2022-08-30 09:30 UTC, fifty-six commented on Scarab/Models/ModLinks.cs
> +
there shouldn't be a blank line between attributes and the corresponding properties/fields

2022-08-30 11:35 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +        public void SelectAll()
I didn't understand

2022-08-30 11:37 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +        private bool _normalSearch = true;
I'm not too sure how these work

2022-08-30 11:37 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +            TagList = new ObservableCollection<string>()
Where should we get them from then? The XML schema?

2022-08-30 11:39 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +                    if (mod.HasIntegrations)
Wdym pattern matching

2022-08-30 14:59 UTC, TheMulhima commented on Scarab/Models/ModItem.cs
> +        public string[]   Integrations { get; }
should be fixed

2022-08-30 15:00 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +            List<ModItem> AllDependents = new();
made it into `dependants`

2022-08-30 15:00 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +        private bool RecursiveCheckDependency(ModItem Mod, ModItem ToSearchDependencyMod)
should be fixed

2022-08-30 15:02 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +        private ModItem? GetMod(string name)
made a new dict that i populate in the constructor

2022-08-30 15:04 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +        private void DisplayModsCorrectly()
what should it be named? like FilterMods?

2022-08-30 15:06 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +        private bool RecursiveCheckDependency(ModItem Mod, ModItem ToSearchDependencyMod)
should it go to ModItem class then? but then i'd have to pass in the ModItem dictionary for the mod lookup

2022-08-30 15:14 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +        public void SelectAll()
will this work better?
```cs
public void SelectMods(int modviewState)
{
    _modViewState = (ModViewState)modviewState;
    DisplayModsCorrectly();
}
```

```xml
<MenuItem Header="All" Command="{Binding SelectMods}" CommandParameter="0" DockPanel.Dock="Top" ToolTip.Tip="Show all available mods"/>
<MenuItem Header="-" DockPanel.Dock="Top" />
<MenuItem Header="Installed" Command="{Binding SelectMods}" CommandParameter="1" DockPanel.Dock="Top" ToolTip.Tip="Show all installed mods"/>
<MenuItem Header="-" DockPanel.Dock="Top" />
<MenuItem Header="Enabled" Command="{Binding SelectMods}" CommandParameter="2" DockPanel.Dock="Top" ToolTip.Tip="Show all installed and enabled mods"/>
<MenuItem Header="-" DockPanel.Dock="Top" />
<MenuItem Header="Out of date" Command="{Binding SelectMods}" CommandParameter="3" DockPanel.Dock="Top" ToolTip.Tip="Show all mods that need updating"/>
<MenuItem Header="-" DockPanel.Dock="Top" />
```

2022-08-30 15:15 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +        private ModItem? GetMod(string name)
see line 107 `_modnameDictionary = _allModItems.ToDictionary(x => x.Name, x => x);`

2022-08-30 21:22 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +            TagList = new ObservableCollection<string>()
got the tags like this instead
```cs
//get all tags on the mods
TagList = new ObservableCollection<string>()
{
    "All Tags" //this isn't a tag but we need it for the combobox
};
foreach (var mod in _allModItems)
{
    if (mod.Tags is null) continue;
    foreach (var tag in mod.Tags)
    {
        if (!TagList.Contains(tag))
        {
            TagList.Add(tag);
        }
    }
}
```

2022-08-30 21:22 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +        public void SelectAll()
I'm not sure the above solution is ideal so I didn't push it to repo yet

2022-08-31 19:24 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +        public void SelectAll()
well i found out `CommandParameter="{x:Static viewModels:ModViewState.All}"` is legal so i think its a better solution

2022-08-31 19:29 UTC, TheMulhima commented on Scarab/ViewModels/ModListViewModel.cs
> +                    if (mod.HasIntegrations)
made it into `if (mod.Integrations is not null)`

2022-10-14 14:39 UTC, closed without merging