Ask for confirmation before removing a mod
fifty-six/Scarab pull request #141
Opened 2023-03-05 19:22 UTC by Hussain-Aziz

- only ask for confirmation before disabling/uninstalling if it has dependents that are installed and enabled.

- used code from #110 by @TheMulhima

2023-03-06 18:40 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +            var dependentsString = string.Join(", ", dependants.Select(x => x.Name));
Don't include `String` in variable names, that's what types are for

2023-03-06 18:40 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +            //return whether or not yes was clicked. Also don't remove mod when box is closed with the x
Keep spaces after `//`

2023-03-06 18:40 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +                text: $"The mods {dependentsString} are dependent on {modName} being installed and enabled. Do you still want to continue?",
I think saying 'requires/needs' over 'is dependent' would be easier for an end user.

2023-03-06 18:41 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +                title: "Warning! This mod has dependents.",
Something like "This mod is required for other mods to function!"

2023-03-06 18:41 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +                //to reset the visuals of the toggle to the correct value
Same thing about comment style

2023-03-06 18:42 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +            if (!item.Installed ||
I'd prefer more explicit control flow over short-circuiting here

2023-03-06 18:47 UTC, fifty-six requested changes

2023-03-06 18:47 UTC, fifty-six commented on Scarab/Services/ReverseDependencySearch.cs
> +            if (dependency == targetMod) return true;
Put return true on a separate line

2023-03-06 18:47 UTC, fifty-six commented on Scarab/Services/ReverseDependencySearch.cs
> +            //if the mod's listed dependency is the targetMod, it is a dependency
Same thing with comment style again

2023-03-07 12:18 UTC, Hussain-Aziz commented on Scarab/ViewModels/ModListViewModel.cs
> +                text: $"The mods {dependentsString} are dependent on {modName} being installed and enabled. Do you still want to continue?",
How is "Vasi is required for Darkness, QoL to function properly. Do you still want to continue?". 

Related to this, should I also bother with 1) placing and before the last mod name and 2) not joining with commas (and joining only with and) if there are only 2 dependents?

2023-03-07 12:19 UTC, Hussain-Aziz commented on Scarab/ViewModels/ModListViewModel.cs
> +                title: "Warning! This mod has dependents.",
Im not closing this because I'm not sure if you want the "Warning!" at the start of the title

2023-03-07 12:24 UTC, Hussain-Aziz commented on Scarab/ViewModels/ModListViewModel.cs
> +            if (!item.Installed ||
I'm not sure what you mean by explicit control flow. Would something like this be better?

```cs
if (item.Installed)
{
    var dependents = _reverseDependencySearch.GetAllEnabledDependents(item).ToList();
    if (dependents.Count > 0)
    {
        var result = await DisplayHasDependentsWarning(item.Name, dependents);
        if (result) // if user selected they want to continue with the action
        {
            await InternalUpdateInstallAsync(item, f);
        }
    }
    else
    {
        await InternalUpdateInstallAsync(item, f);
    }
}
else
{
    await InternalUpdateInstallAsync(item, f);
}
```

I personally dislike this because it calls InternalUpdateInstallAsync 3 times

2023-03-07 12:46 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +            if (!item.Installed ||
The first two together is fine, just wanted the warning to be its own check instead of short-circuited. And yeah I prefer the returns to elses generally.

2023-03-07 12:46 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +                title: "Warning! This mod has dependents.",
Yeah that's fine

2023-03-07 12:47 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +                text: $"The mods {dependentsString} are dependent on {modName} being installed and enabled. Do you still want to continue?",
It'd be nice but isn't totally necessary. That wording sounds perfect though

2023-03-07 12:47 UTC, Hussain-Aziz commented on Scarab/ViewModels/ModListViewModel.cs
> +            if (!item.Installed ||
I wouldn't want to put first 2 checks together because if Item is uninstalled the `GetAllEnabledDependents` call is wasted. But that might not matter? Idk

2023-03-07 12:54 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +            if (!item.Installed ||
Ah ok. It's fine then, might see if i can make it "prettier" later but reasoning makes sense

2023-03-07 12:54 UTC, merged

2023-03-07 12:55 UTC, fifty-six commented
Thanks for the PR!