Added about button (#84)
fifty-six/Scarab pull request #146
Opened 2023-04-16 06:47 UTC by CharlesGameDev

Added an about button that shows the current Scarab version and the GitHub link.
Answers issue #84

2023-04-17 02:00 UTC, Cavernosa requested changes

2023-04-25 14:36 UTC, fifty-six requested changes

2023-04-25 14:36 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +            string aboutText = Resources.PU_About;
Just method chaining would be nicer here

2023-04-25 14:36 UTC, fifty-six commented on Scarab/ViewModels/ModListViewModel.cs
> +            aboutText = aboutText.Replace("1", Assembly.GetEntryAssembly().GetName().Version.ToString());
It's not gonna be relevant so you can suppress the null warning here with `!`. Alternatively `?` would be fine (maybe preferred, given I was gonna look into AOT stuff) and just default to "Unknown" with `??`.

2023-04-25 14:36 UTC, fifty-six commented
What Cavernosa said also seems good to address, aside from that this looks great though.

2023-09-06 06:19 UTC, fifty-six commented
Went with a tab in the latest release instead, though thanks for the PR

2023-09-06 06:19 UTC, closed without merging